# Generated by Django 4.2.13 on 2024-07-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_remove_trade_payment_delete_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.AlterField(
            model_name='stock',
            name='company',
            field=models.CharField(help_text='Enter the company name', max_length=200, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='profit',
            field=models.DecimalField(decimal_places=2, help_text='What is the profit margin?', max_digits=8, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='How many stocks do you own?', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(help_text='Enter the company ID', max_length=20, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='How much are the stocks worth?', max_digits=8, verbose_name='Value'),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='What does this company do?', verbose_name='Description')),
                ('est_date', models.DateField(help_text='When was this company established?', verbose_name='Establishment Date')),
                ('company', models.ForeignKey(help_text='Enter company name', on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='Company')),
            ],
        ),
    ]
