# Generated by Django 4.2.13 on 2024-07-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_date_remove_stock_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='profit',
        ),
        migrations.AddField(
            model_name='stock',
            name='balance',
            field=models.FloatField(default=100000.0, help_text='What is your current balance?', verbose_name='Current Balance'),
        ),
    ]
