# Generated by Django 4.2.14 on 2024-07-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stock_profit_stock_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
